title: SproutSpace: AI Powered Plant Health Diagnostics
description: An intuitive mobile application leveraging AI powered multispectral imaging to help home gardeners diagnose plant health issues and receive actionable recommendations.
theme: minima
