remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "SproutSpace: AI–Powered Plant Health Diagnostics for Home Gardeners"
description: "An intuitive mobile application leveraging AI–powered multispectral imaging to help home gardeners diagnose plant health issues and receive actionable recommendations."
